version: "3.7"

services:
  img_create:
    environment:
      - FLAVOR=ubuntu22.04
      - REPOFOLDER=/tmp/blubber/
    build: .    
    tty: true
    volumes:
      - ./download:/tmp/download
      - ../rpi:/tmp/blubber/rpi
      - ../common:/tmp/blubber/common
      - ./output:/tmp/output
      - ./images:/tmp/images
